subcomponents:
  hello-rings-featureydawgie:
    config:
      branchName: featureydawgie
      buildDate: "2019-07-09T21:24:59.4221535Z"
      buildId: "4906"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featureydawgie-4906
