subcomponents:
  hello-rings-featurea:
    config:
      author: GitHub
      branchName: featurea
      buildDate: "2019-06-25T09:08:50.3790219Z"
      buildId: "4322"
      commitId: b11b2ee250b44d25cf5e86a8b35e858af6852a9f
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurea-4322
  hello-rings-featurey:
    config:
      branchName: featurey
      buildDate: "2019-06-27T11:41:27.2105946Z"
      buildId: "4583"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurey-4583
  hello-rings-featurez:
    config:
      author: GitHub
      branchName: featurez
      buildDate: "2019-06-25T15:04:03.5413203Z"
      buildId: "4478"
      commitId: ecc42ec8cc1fb0364e9694991cf5d49b44ee9eee
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurez-4478
  hello-rings-master:
    config:
      author: Samiya Akhtar
      branchName: master
      buildDate: "2019-06-26T13:10:43.2044379Z"
      buildId: "4546"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-master-4546
